version: '3.5'
services:
  pse-proxy:
    image: kkisalaya/pse-proxy:dev
    container_name: pse-proxy
    user: root
    environment:
      - INVISIRISK_JWT_TOKEN=WkxFvX05QDdcVUbN4AQPFNKVUo91hPpicvDitZL3RoJGEeKzzOSGaKXMeC34nEJbehBsxlT5DMF_RZ8-RQ1Lhg
      - PSE_DEBUG_FLAG=--alsologtostderr
      - POLICY_LOG=t
      - INVISIRISK_PORTAL=http://app.dev.veribom.com/

  node-app-1:
    image: node:18-alpine
    container_name: node-app-1
    user: root
    cap_add:
      - NET_ADMIN
    environment:
      - SERVICE_NAME=node-app-1
    volumes:
      - ./entrypoints:/app/entrypoints
      - ./package.json:/app/package.json
      - ./src/project1/build.sh:/app/build.sh
    working_dir: /app
    entrypoint: ["/app/entrypoints/entrypoint.sh"]
      #    command: ["tail -f /dev/null"]


