name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build and run docker compose
      run: docker compose up
        
    - name: Check running containers
      run: docker ps -a
      
    - name: Stop containers
      run: docker compose down
