name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    services:
      # Label used to access the service container
      pse:
        image: kkisalaya/pse-proxy:dev
        env:
          PSE_DEBUG_FLAG: --alsologtostderr
          POLICY_LOG: t
          INVISIRISK_JWT_TOKEN: WkxFvX05QDdcVUbN4AQPFNKVUo91hPpicvDitZL3RoJGEeKzzOSGaKXMeC34nEJbehBsxlT5DMF_RZ8-RQ1Lhg
          INVISIRISK_PORTAL: https://app.dev.veribom.com/
          #POLICY_AUTH_TOKEN: ${{ secrets.POLICY_AUTH_TOKEN }}
          #POLICY_URL: https://app.dev.veribom.com/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # OPENAI_AUTH_TOKEN: ${{ secrets.OPENAI_AUTH_TOKEN }}
          #PSE_DEBUG_FLAG: --alsologtostderr
          #POLICY_LOG: t
    container:
      image: node:18-alpine
      options: --cap-add=NET_ADMIN
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: invisirisk/pse-action@v1
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
